languageCode = "en-us"
title = "person.unsure"
baseURL = "http://person.unsure.tech/"
enableEmoji = true
theme = "unsure"

[params]
description = "Who can ever be so sure?"
author = "person unsure"

[params.unsure]
dark = true

[[menu.main]]
name = 'github'
url = 'https://github.com/danielma'

[[menu.main]]
name = 'twitter'
url = 'https://twitter.com/personunsure'

[[menu.main]]
name = 'about'
url = '/'

[[menu.main]]
name = 'projects'
url = '/projects'